navikt/sosialhjelp-innsyn

package-lock.json
package.json
src/App.tsx
src/configureStore.ts
src/pages/SaksStatus.tsx
src/redux/innsynsdata/innsynsDataActions.ts
src/redux/innsynsdata/innsynsdataReducer.ts
src/redux/reduxTypes.ts
src/rootReducer.ts
src/utils/restUtils.ts
src/utils/setPath.ts

Bruke samme async action creators og setPath i redux som på søknadsapp.

DIGISOS-1316 Hente data fra REST tjenester

---

package-lock.json
src/App.tsx
src/configureStore.ts
src/utils/restUtils.ts

Er en forutsetning for at navikt/sosialhjelp-test-proxy#6 skal fungere.

DIGISOS-1329: Legg til pathname-agnostisk routing og API-resolving

---

src/utils/restUtils.ts

Også på kall mot lokal innsyn-api lokalt

Endre context-path til /sosialhjelp.

---

package-lock.json
package.json
src/App.test.tsx
src/components/ikoner/TodoList.tsx
src/components/ikoner/UploadFile.tsx
src/components/oppgaver/FilView.tsx
src/components/oppgaver/FileView.test.ts
src/components/oppgaver/OppgaveView.tsx
src/components/oppgaver/Oppgaver.tsx
src/components/oppgaver/oppgaver.less
src/innsyn/SaksStatus.tsx
src/redux/innsynsdata/innsynsDataActions.ts
src/redux/innsynsdata/innsynsdataReducer.test.ts
src/redux/innsynsdata/innsynsdataReducer.ts
src/utils/restUtils.ts

Opplasting av vedlegg og metadata til innsyn api

DIGISOS-1380 Vedleggsopplasting

---

src/components/soknadsStatus/SoknadsStatus.tsx

https://jira.adeo.no/browse/DIGISOS-1516

Endrer tittel fra 'Vedtaksbrev' til 'Vedtak'

---

src/components/ikoner/RemoveCircle.tsx
src/components/main-nav/mainNav.less
src/components/oppgaver/FilView.tsx
src/components/oppgaver/OppgaveView.tsx
src/components/oppgaver/oppgaver.less
src/components/soknadsStatus/SoknadsStatus.tsx
src/components/soknadsStatus/soknadsStatus.less

fikser styling

---

src/components/historikk/Historikk.tsx
src/redux/innsynsdata/innsynsdataReducer.ts

mottar link tekst fra backend sammen med url

---

package-lock.json
package.json
src/index.tsx

Legger til core-js@3 som polyfiller object.assign ++ for IE11.

Legger inn core-js@3 og importerer denne i index

---

public/dev_index.html
src/components/banner/BigBanner.tsx
src/components/brodsmuleSti/BrodsmuleSti.tsx
src/saksoversikt/banner/SaksoversiktBanner.tsx
src/utils/restUtils.ts

* Oppdatere lenker mot dittnav
* Lar DittNav i brødsmulesti endre seg basert på miljø

Oppdaterer lenke i brødsmulesti

---

src/App.less
src/components/arkfanePanel/mainNav.less
src/components/oppgaver/oppgaver.less

Fjernet text-decoration: none;

---

src/saksoversikt/Saksoversikt.tsx

Endret feilmelding når vi ikke kan hente søknader fra enten innsyn-api eller soknad-api

---

src/components/oppgaver/OppgaveView.tsx
src/components/vedlegg/EttersendelseView.tsx
src/tekster/tekster.ts
src/utils/vedleggUtils.ts

- La til validering av ulovlige tegn i filnavn
- Forbedret logikk og utseende rundt feilmeldinger som klienten fanger opp.
(Skal gå inn til master men lar den gå mot feature/endre_feilmelding frem til den er merget med master, fordi jeg branchet ut fra feil branch i farta :))

La til validering av ulovelige tegn i filnavn

---

package-lock.json
package.json
src/App.tsx
src/utils/restUtils.ts

Samme oppsett og config som for søknaden, og opprettet eget prosjekt i Sentry.

Legger til logging til Sentry lokalt og på q miljøer

---

.github/workflows/build.yml
Dockerfile
README.md

Flytter npm ci/test/build til github actions  fra dockerfile.
Bruker actions/cache for å cache dependencies.

Bygg endringer

---

src/components/oppgaver/Oppgaver.tsx
src/components/vedlegg/EttersendelseView.tsx

DIGISOS-1692 Innsyn-api: Validere at antall filer ikke er 0 på backend.

---

.prettierrc.js
package-lock.json
package.json
src/components/oppgaver/FileView.test.ts
src/components/oppgaver/OppgaveView.tsx
src/components/oppgaver/Oppgaver.tsx
src/components/oppgaver/oppgaver.less
src/components/vedlegg/EttersendelseView.tsx
src/index.tsx
src/tekster/tekster.ts
src/utils/restUtils.ts
src/utils/vedleggUtils.test.ts
src/utils/vedleggUtils.ts

Reverts navikt/sosialhjelp-innsyn#107

Revert "Fix/digisos 1572 ettersende store vedlegg henger"

---

package-lock.json

Patcher en del sårbarheter vi får fra blant annet `react-scripts`

Kjører npm audit fix for å patche sårbarheter

---

.github/workflows/npm_audit.yml

Samme action som er satt opp for søknaden.

Legger til action som kjører npm audit ved push til branch

---

package-lock.json
src/App.tsx
src/components/hotjarTrigger/HotjarTrigger.js
src/configureStore.ts
src/utils/restUtils.getUrl.test.ts
src/utils/restUtils.ts

Mange nye tester på getUrl-funksjoner for alle miljøer
getBaseUrl
getSoknadUrl
getDittNavUrl
getSwaggerUrl (gir nå tom verdi i prod)

Fikset getUrl i digisos.labs + masse tester

---

CODEOWNERS

Slik at teamdigisos automatisk blir reviewer av PR

La til CODEOWNERS-fil

---

src/components/oppgaver/OppgaveView.tsx
src/components/vedlegg/EttersendelseView.tsx
src/utils/vedleggUtils.test.ts
src/utils/vedleggUtils.ts

Mer logging er lagt til pluss en null check.

DIGISOS-1883 Innsyn: Fra Logger: Mangler metadata.json eller det er mismatch

---

src/index.less

Vi bruker simple-footer i soknad og innsyn.

DIGISOS-1922 Innsyn og Soknad: Skjul del-skjerm 2

---

src/index.less

Prøvde først å disable med ENV variabel i `pus-decorator`, men det fungerte ikke. Legger derfor inn en skjuling med CSS inntil vi finner ut av hvorfor PUS ikke leser env-variabler / får skrevet om til å bruke dynamisk innlastet dekoratør i stedet.

Disable frida stygg hack

---

.github/workflows/build.yml

Løsning for bedre arbeidsflyt fram til vi finner en bedre løsning (trekker ut i egen action, templates kommer og gjør alt bedre, e.l.)

Bygg alle commits i alle brancher

---

src/components/oppgaver/ReturnErrorMessage.tsx
src/tekster/tekster.ts
src/utils/vedleggUtils.ts

- utvidet if sjekk til å ta dette i bruk

- endret tekster til å være mer spesifikt når en fil feiler

---

src/components/oppgaver/ErrorMessage.tsx
src/components/oppgaver/ErrorMessageTitle.tsx
src/components/oppgaver/ReturnErrorMessage.tsx
src/utils/vedleggUtils.ts

- feilmeldinger skal nu vises en omgangen når 1 fil har 2/3 feiler
- Utvider komponenter slik at det er mer leselig

Bedre feilmeldinger og fremvisning av feilmeldinger

---

src/redux/innsynsdata/innsynsDataActions.ts

Legger til url i logWarningMessage for å forbedre logg beskjed i networks

Forbedre logg beskjed

---

package-lock.json
package.json
src/components/driftsmelding/Driftsmelding.test.ts

bumper pakker og fikser typescript-klage

Npm update

---

README.md
package-lock.json
package.json
src/components/driftsmelding/Driftsmelding.test.ts

Reverts navikt/sosialhjelp-innsyn#270
lurer på om jeg brakk vedleggssending! reverter for å teste

Revert "Npm update"

---

README.md
package-lock.json
package.json
src/components/driftsmelding/Driftsmelding.test.ts

Ser ut som denne var i orden likevel, men venter med prodsetting til etter langhelg!

Npm updates

---

package-lock.json
package.json
src/components/arkfanePanel/ArkfanePanel.tsx
src/components/eksternLenke/EksternLenke.tsx
src/components/forelopigSvar/ForelopigSvar.tsx
src/components/historikk/Historikk.tsx
src/components/oppgaver/Oppgaver.tsx
src/components/soknadsStatus/SoknadsStatus.tsx
src/components/vilkar/Vilkar.test.ts
src/innsyn/SaksStatus.tsx
src/saksoversikt/Saksoversikt.tsx
src/saksoversikt/SaksoversiktDineSaker.tsx
src/utbetalinger/Utbetalinger.tsx
src/utils/amplitude.ts

Prøver meg på noen amplitue målinger. Branchen ligger i dev-gcp. Og målinger ligger her https://analytics.amplitude.com/nav/dashboard/9t3j0ws (grafene viser resulteter for  NAV default preprod miljøet).
Litt usikker på målinger der jeg har prøvd å lage antall klikk relativt til hvor mange som har mulighet til å klikke. https://analytics.amplitude.com/nav/chart/fffxyax?source=dashboard 
Feks måler jeg antall klikk på "vis foreløpig svar", men det er jo ikke alle saker som har mottat foreløpig svar. Men siden jeg måler på UNIQUES vil harMottattForeløpigSvar bare måles én per gang bruker uansett antall saker bruker har. 
Tar gjerne en diskusjon på dette :)

Logging amplitude

---

src/components/vedlegg/EttersendelseView.tsx

Velg fil-knappen i ettersendelse bruker AddFileButton-komponenten.

Ettersendelse bruker AddFileButton-komponent

---

src/components/oppgaver/AddFileButton.tsx
src/components/oppgaver/DokumentasjonEtterspurtView.tsx
src/components/oppgaver/DokumentasjonKravView.tsx
src/components/oppgaver/FileItemView.tsx
src/components/vedlegg/EttersendelseView.tsx
src/saksoversikt/SaksoversiktDineSaker.tsx

Co-authored-by: jorgen.elden.lindgren@nav.no

Bytter ut knapp med Button

---

nais/prod/prod-sbs.json

prod-sbs.nais.io er "reserved for platform services"

fjern gammel ingress

---

.github/workflows/deploy_dev.yml

Fjerner samtidig repository dispatch

Miljø i github actions jobbnavn

---

src/components/feilside/Feilside.tsx
src/innsyn/SaksStatus.tsx
src/redux/innsynsdata/innsynsDataActions.ts
src/tekster/tekster.ts
src/utils/restUtils.ts

Håndterer 404 feil fra backend, viser 404 feilside

---

src/components/oppgaver/IngenOppgaverPanel.tsx
src/components/vilkar/OppgaveInformasjon.tsx
src/components/vilkar/Vilkar.test.ts
src/components/vilkar/VilkarUtils.ts

* "Du kan ha vilkår" vises bare hvis det finnes saker (og disse har status `INNVILGET`/`DELVIS_INNVILGET`
* "Du har ingen oppgaver" vises bare hvis det ikke finnes oppgaver og det finnes en sak med status `AVVIST`/`AVSLATT` eller det ikke finne saker

Mer fikser på infoboksene på Dine oppgaver

---

src/saksoversikt/SaksoversiktDineSaker.tsx
src/utbetalinger/Periodevelger.tsx
src/utbetalinger/SavnerUtbetalingPanel.tsx

Utvider til 15 mnd lagringstid og fjerner filtering på Dine Søknader

---

package-lock.json
src/components/oppgaver/Oppgaver.tsx
src/components/oppgaver/accordions/DokumentasjonkravAccordion.tsx
src/components/oppgaver/accordions/VilkarAccordion.tsx

når henting av utbetalinger for å filtrere oppgaver feiler, vises kun alertstripe med feilmelding istedet for en hel feilside

Feilmelding oppgaver

---

.github/workflows/deploy_dev.yml

Setter cluster basert på config-file i stedet. Ikke dritpent, men har ikke funnet noen finere måte å gjøre det på.
Hvis dette er greit kan vi gjøre tilsvarende i andre apper og.

Deploy til dev setter cluster etter config-file input 

---

.github/workflows/nattlig_redeploy.yml

- steg 1 i å skru av helt (sletter også appen med `kubectl delete app`

Restarter ikke labs om natta

---

nais.yaml
nais/dev/dev-sbs.json
nais/dev/dev.json
nais/dev/labs-gcp.json
nais/dev/mock.json
nais/prod/prod-gcp.json
nais/prod/prod-sbs.json
server.js

Egendefinert logouturl via dekoratøren

---

src/components/meldingstjenesteInfo/MeldingstjenesteInfo.tsx
src/redux/innsynsdata/innsynsdataReducer.ts
src/saksoversikt/Saksoversikt.tsx

Skjuler innganger til meldingstjenesten for de som ikke har onboardet, siden den snart skrus av.

Skjuler innganger til meldingstjenesten for ikke onboardede

---

src/App.tsx
src/index.css

Slik at det ikke ser så kjipt ut når siden laster

sørger for at footer blir sticky i bunn

---

.github/workflows/deploy_dev.yml
.github/workflows/nattlig_redeploy.yml

Fjerner også nattlig restart i dev-sbs

Fjerner mulighet for å deploye til dev-sbs.

---

package-lock.json
package.json
src/components/timeoutbox/LoggetUt.tsx
src/components/timeoutbox/Nedtelling.tsx
src/components/timeoutbox/TimeoutBox.tsx
src/components/timeoutbox/timeoutbox.css
src/hooks/useInterval.ts
src/index.css
src/innsyn/SaksStatus.tsx
src/tekster/tekster.ts
src/utils/restUtils.ts
src/utils/timeoutUtils.ts

- Ny timeout modal som skal dukke opp under `/innsyn/xxx/status` når bruker er inaktivt etter 30 minutter 
- Logikken hentes fra søknaden hvor modalen vises når bruker er inaktivt under søknad opprettelse

Legger til ny modal for timeout

---

README.md

oppdaterer readme

---

src/components/vedlegg/EttersendelseView.tsx

Reverts navikt/sosialhjelp-innsyn#520

Revert "Fikser feil der BACKEND_FEIL_ID ble brukt istedenfor fiksDigisosId"

---

src/components/errors/ErrorMessage.tsx
src/components/oppgaver/AddFileButton.tsx
src/components/oppgaver/DokumentasjonEtterspurtElementView.tsx
src/components/oppgaver/DokumentasjonEtterspurtView.tsx
src/components/oppgaver/DokumentasjonKravView.tsx
src/components/oppgaver/DokumentasjonkravElementView.tsx
src/components/oppgaver/ErrorMessage.tsx
src/components/oppgaver/ErrorMessageTitleNew.tsx
src/components/oppgaver/onSendVedleggClicked.ts
src/components/oppgaver/onSendVedleggClickedNew.ts
src/components/vedlegg/EttersendelseView.tsx
src/redux/innsynsdata/innsynsdataReducer.ts
src/tekster/tekster.ts
src/utils/vedleggUtils.test.ts
src/utils/vedleggUtils.ts

Reverts navikt/sosialhjelp-innsyn#519

Revert "Fikser feilmelding visninger"

---

src/tekster/tekster.ts

Dette ble avklart med André når vi gikk gjennom utseende til feilmeldingene før jul

Endrer på teksten til fil størrelse slik at den er litt mer forklarende

---

src/components/oppgaver/AddFileButton.tsx
src/components/oppgaver/DokumentasjonEtterspurtElementView.tsx
src/components/oppgaver/DokumentasjonEtterspurtView.tsx
src/components/oppgaver/onSendVedleggClicked.ts
src/components/oppgaver/onSendVedleggClickedNew.ts
src/components/vedlegg/EttersendelseView.tsx
src/utils/vedleggUtils.test.ts
src/utils/vedleggUtils.ts

Reverts navikt/sosialhjelp-innsyn#535

Revert "Refaktorerer dokumentasjon etterspurt"

---

src/components/linkButton/LinkButton.module.css
src/components/linkButton/LinkButton.tsx
src/components/vedlegg/FileItemView.tsx
src/components/vedlegg/VedleggModal.tsx
src/components/vedlegg/vedlegg.module.css
src/hooks/useFilOpplasting.ts

- fikser bug der preview av feil fil ble vist ved flere filer lastet opp,
- legger på unik id på filene
- gjør om lenke for å åpne fil til lenkeknapp siden den åpner modal

Bug filepreview

---

src/utils/restUtils.test.ts

begynner å bli en stund siden nais gikk vekk fra istio

fjerner istio-headers test

---

nais/dev/dev.yaml
nais/dev/mock.yaml
nais/prod/prod-gcp.yaml

legger til dekoratøren og ingresser for testmiljø i access policy

Access policy

---

src/components/filopplasting/FilOpplastingBlokk.tsx
src/components/filopplasting/useFilOpplasting.ts

Fikser styling på feilmelding og gjør det mulig at godkjent fil lastes opp når man prøver å laste opp både en godkjent og en ugyldig.

Vedlegg feil style

---

src/components/driftsmelding/Driftsmelding.test.ts
src/components/driftsmelding/Driftsmelding.tsx
src/components/driftsmelding/DriftsmeldingUtilities.ts
src/components/driftsmelding/DriftsmeldingVedlegg.tsx
src/components/ettersendelse/EttersendelseView.tsx
src/components/filopplasting/filopplasting.module.css
src/components/oppgaver/Oppgaver.tsx
src/components/oppgaver/dokumentasjonEtterspurt/DokumentasjonEtterspurtAccordion.tsx
src/components/oppgaver/dokumentasjonEtterspurt/DokumentasjonEtterspurtView.tsx
src/components/oppgaver/dokumentasjonkrav/DokumentasjonKravView.tsx
src/components/oppgaver/oppgaver.module.css
src/locales/nb.json

Viser feilmeldinger for ettersendelse og i toppen av søknader for digisosid som har søknad som feilet

Feilmelding digisosid

---

src/components/Tilgangskontrollside/Tilgangskontrollside.tsx
src/components/appBanner/AppBanner.tsx
src/innsyn/SaksStatus.tsx
src/locales/nb.json
src/saksoversikt/Saksoversikt.tsx
src/saksoversikt/SaksoversiktIngenSoknader.tsx
src/utils/breadcrumbs.ts

trekker ut flere tekster til oversettelse

Spraknokler2

---

public/locales/en/common.json
public/locales/en/utbetalinger.json
public/locales/nb/common.json
public/locales/nb/utbetalinger.json
public/locales/nn/common.json
public/locales/nn/utbetalinger.json
src/pages/[id]/status.tsx
src/pages/utbetaling.tsx
src/saksoversikt/SaksoversiktDineSaker.tsx

Legger tilbake varslings banneren på grunn av dette:
[Fiks-plattformen: Planlagt vedlikehold 07.05.24 07:00 - 10:00]
THIS IS A SCHEDULED EVENT May 7, 07:00 - 10:00 CESTMay  6, 09:45 CEST
Scheduled - Vedlikeholdet vil medføre ustabilitet og potensielt korte perioder med utilgjengelighet på Fiks-tjenestene.
Masseutsendinger i SvarUt anbefaler vi at gjøres utenom vedlikeholdsvinduet.
Vi beklager ulempene dette kan medføre.

varslings banner igjen

---

src/utils/amplitude.ts

Ifbm refaktor av utbetalinger tenkte jeg det hadde vært kjekt med en sterkere typet variant av logAmplitudeEvent.

lager en sterkere typet variant av logAmplitudeEvent

---

src/pages/[id]/status.tsx

Aller helst burde Fiks (som dokumentasjonen deres sier) returnere 403 ved forsøk på å hente søknadsdata for en søknad de ikke eier, men det gir 404.
Uansett forsøker vi en canary-request mot digisosId før vi utløser ørten forskjellige kall som støyer i logger. Dersom søknadstatus ikke kan hentes, logger vi en advarsel og returnerer bruker til forsida.

Redirect til forside om ugyldig fiksDigisosId

---

messages/en.json
messages/nb.json
messages/nn.json
src/app/[locale]/Providers.tsx
src/app/[locale]/klage/opprett/[klageId]/page.tsx
src/app/[locale]/landingsside/page.tsx
src/components/breadcrumbs/ClientBreadcrumbs.tsx
src/hooks/useUpdateBreadcrumbs.ts
src/utils/breadcrumbs.ts

Flytter logikken for å sette riktig breadbcrumbs til hver page.tsx istedenfor dynamisk basert på current path, da logikken for å støtte dynamiske urler ble for komplisert.

Add breadrumbs to Klage-page.

---

innsyn-api.json
messages/en.json
messages/nb.json
messages/nn.json
src/app/[locale]/soknad/[id]/_components/Soknad.tsx
src/app/[locale]/soknad/[id]/_components/dokumenter/Dokumenter.tsx
src/app/[locale]/soknad/[id]/_components/dokumenter/VedleggListe.tsx

Legg til original søknad i dokumenter-liste

---

messages/en.json
messages/nb.json
messages/nn.json
src/app/[locale]/soknad/[id]/_components/saker/vedtak/KlageInfo.tsx
src/app/[locale]/soknad/[id]/_components/saker/vedtak/Vedtak.tsx

Legger til klage-knapp (bak feature toggle) som tar bruker til klageskjema.
Endrer litt på stylingen til klagebokse.

Add klage button to soknad.

---

innsyn-api.json
messages/en.json
messages/nb.json
messages/nn.json
src/app/[locale]/klage/opprett/[id]/[vedtakId]/_components/klageForm.tsx
src/app/[locale]/klage/status/[id]/[vedtakId]/_components/prosessenVidere.tsx
src/app/[locale]/klage/status/[id]/[vedtakId]/page.tsx

Hent ut klage fra backend og vis lenke til klage.pdf.
