navikt/sosialhjelp-innsyn

.circleci/config.yml

Bruker digisos-ci til å lage tag+release slik at releasen (Docker-image) blir knyttet til riktig branch+commit.

DIGISOS-1319: Fiks tag+release på riktig branch med GitHub app

---

src/innsyn/SaksStatus.tsx
src/utils/restUtils.ts

Måtte subscribe på `innsynsdata.restStatus.saksStatus` i stedet for `innsynsdata.restStatus` for at effekten skal trigge når det første kallet endrer rest-status.

Ikke utfør alle kallene mot API hvis ett feiler

---

src/components/oppgaver/FilView.tsx
src/components/oppgaver/OppgaveView.tsx
src/components/vedlegg/EttersendelseView.tsx
src/redux/innsynsdata/innsynsdataReducer.ts

Bruker index til å fjerne filer fra lista over filer som skal lastes opp i stedet for filnavn, slik at ikke trykk på fjern/søppelbøtte fører til at alle filer med samme navn fjernes.

Bruk index til å fjerne filer fra filvisning i stedet for filnavn

---

src/saksoversikt/sakpanel/SakPanel.tsx

nytt forsøk på å finne ut hvorfor frontend kaller backend med fiksDigisosId = undefined

ekstra sjekk i SakPanel om fiksDigisosId === null || undefined

---

src/redux/innsynsdata/innsynsdataReducer.ts

Fiks filtrering av filer for ettersendelse. Den forrige måten å gjøre det på feilet fordi den sjekker statusene før de har blitt oppdatert.

Fiks feilet filfiltrering fornuftigere

---

src/tekster/tekster.ts

"Søknaden er ferdig behandlet" skal vises, ikke "Søknaden behandles ikke". 
Dette er i henhold til beskrivelsen i https://jira.adeo.no/browse/DIGISOS-1607

Nå skal status.behandles_ikke vise riktig tekst

---

src/utils/restUtils.ts

Fordi backend sin json-parser mener at JSON alltid skal være UTF-8 og krever derfor dette.

Inkluderer charset=utf-8 når contentType er application/json

---

src/components/oppgaver/OppgaveView.tsx
src/components/oppgaver/Oppgaver.tsx
src/redux/innsynsdata/innsynsDataActions.ts
src/redux/innsynsdata/innsynsdataReducer.test.ts
src/redux/innsynsdata/innsynsdataReducer.ts

Ved opplasting av vedlegg gjør vi nye kall mot backend for å hente ut oppdatert state for oppgaver. Denne staten overskriver det vi har under "oppgaver" i appen vår allerede, og fører til at brukere som eks. har lagt til filer for opplasting under flere oppgaver mister disse når hen trykker på "Last opp".
Ved å kun hente oppdatert state for den oppgaven vi har lastet opp filer til, slipper vi å oppdatere state for de andre oppgavene.
https://github.com/navikt/sosialhjelp-innsyn-api/pull/170 må være i prod først, slik at frontend ikke prøver å kalle endepunkter som ikke eksisterer.

Tar i bruk nytt endepunkt i backend for å hente enkeltoppgaver etter opplasting

---

src/components/oppgaver/OppgaveView.tsx
src/components/vedlegg/EttersendelseView.tsx
src/redux/innsynsdata/innsynsDataActions.ts
src/redux/innsynsdata/loggActions.ts
src/utbetalinger/service/useUtbetalingerService.ts
src/utils/restUtils.ts
src/utils/vedleggUtils.ts

Tidligere var det en sirkulær avhengighet, 
- der **restUtils.ts** hentet **logErrorMessage** fra **innsynsDataActions.ts**
- og **innsynsDataActions.ts** hentete **REST_STATUS** fra **restUtils.ts**
Dette gjorde blandt annet at tester man ønsker å lage med en import fra en av disse vil faile. Generelt kan sirkulære avhengigheter også få uventede konsekvenser.
Fikset det ved å dra **loggActions.ts** ut fra **innsynsDataActions.ts** slik at **restUtils.ts** ikke lenger har en avhengighet til **innsynsDataActions.ts**

Fikser sirkulær avhengighet mellom restUtils.ts og innsynsDataActions.ts

---

src/components/hotjarTrigger/HotjarTrigger.js
src/innsyn/SaksStatus.tsx
src/innsyn/saksStatusUtils.test.ts
src/innsyn/saksStatusUtils.ts
src/redux/innsynsdata/innsynsdataReducer.ts
src/saksoversikt/Saksoversikt.tsx

Endrer også triggernavn (sjekker med Wilhelm først)
Klargjør også en egen trigger for Bergen, som vi ønsker å ha i overgangen når vi går fra å kun ha Bergen på innsyn til å også få nye kommuner. Må vente på at backend sender kommunenummer i /kommune først
Edgecaser:
Dersom kommuneinfo ikke blir hentet korrekt antar vi at kommunen ikke er på innsyn.
Dersom kommunen har innsyn midlertidig deaktivert, bruker vi hotjartriggeren medInnsyn

Flytte hotjar fra landingsside til søknadssiden.

---

package-lock.json
package.json

Ved oppgradering av `react-scripts` klagde npm på at `webpack` ikke lengre fantes. Jeg har prøvd å grave litt i hvorfor men fant ikke ut hva det er som har skjedd. Har midlertidig lagt inn `webpack` som en egen dev-dependency. Følger samtidig med på når neste versjon av react-scripts blir lansert og om dette blir løst da. :)
`craco-less` er oppgradert og låst til `1.16.0`. Versjon `1.17.0` tar i bruk en ny versjon av `less-plugin` som krever endringer i konfigurasjon på vår side.

Oppgraderer react-scripts og craco

---

package-lock.json
package.json

Fjerner også eksplisitt avhengighet til webpack siden vi får denne fra react-scripts, og kjører en `npm audit fix` for å patche andre sårbarheter.

Upgrade react scripts

---

src/saksoversikt/SaksoversiktDineSaker.tsx
src/utbetalinger/service/useUtbetalingerExistsService.ts

⚠️ NB: Kan ikke bli deployet før etter https://github.com/navikt/sosialhjelp-innsyn-api/pull/207 ⚠️ 
Tar i bruk nytt endepunkt for å sjekke om en bruker har utbetalinger.
Denne sjekken er raskere fordi den returnerer true ved første resultat. Tidligere fikk denne sjekken ugyldig token i q0 fordi, den brukte mer enn 2 minutter. Nå tok den 8.9 sekunder.
Funksjonaliteten er viktigst for testing med Nathalie og for brukere som har veldig mange søknader.

Ta i bruk nytt endepunkt for raskere utbetalings-sjekk på landingssiden

---

src/components/hotjarTrigger/HotjarTrigger.js
src/innsyn/SaksStatus.tsx
src/innsyn/saksStatusUtils.test.ts
src/innsyn/saksStatusUtils.ts
src/redux/innsynsdata/innsynsdataReducer.ts

Endrer hotjartrigger etter avtale med Wilhelm:
* Ingen hotjartrigger dersom søknaden er mindre enn 1t gammel (pga gir falske positive, folk er fornøyde rett etter de har sendt inn søknaden)
* Søknader med deaktivert innsyn trigger hotjar uten innsyn
* Søknader med aktivert innsyn og med innsynsfil trigger hotjar med innsyn
* Ingen hotjartrigger dersom kommunen har aktivert innsyn, men det ikke er noen innsynsfil på søknaden. Dette fordi det er umulig for oss å vite om dette er en ny søknad som snart vil få innsyn, eller om dette er en søknad som ble sendt inn før kommunen aktiverte innsyn, og dermed aldri vil få innsynsfil.
(NB: per i dag er det ingen hotjartrigger ved papirsøknader, men det er heller ingen som sender innsyn papirsøknader enda)

Endrer hotjartrigger etter avtale med Wilhelm:

---

src/saksoversikt/Saksoversikt.tsx

* Kun vise feilmelding, ikke feilside om søknader fra innsyn inn kan hentes. 
* Rename variabler så de er mer konsekvente og lage litt luft mellom bolker så det blir lettere å lese hva som hører sammen.

Ikke vise feilside om innsyndata ikke kan hentes fra landingssiden

---

Dockerfile
nais.yaml

som ikke ser ut som ble brukt av noe annet enn dekoratøren. 
(ble lagt til da vi gikk over på nais for 2 år siden. Ble nok dratt med i en copy-paste)

Fjerner unleash_url

---

src/components/brodsmuleSti/BrodsmuleSti.tsx
src/utils/navigasjon.ts

Vi får en del feilmeldinger i Sentry på at `history.push` ikke er en funksjon. 
Siden vi bør ta i bruk nav.no dekoratøren sin brødsmulesti i alle appene våre bytter jeg bare ut onClick metodene her med vanlig href foreløpig.

Fjerner onClick metoder på lenker i brodsmulesti siden disse gir en del feilmeldinger i Sentry og brødsmulesti på sikt skal byttes ut med dekoratør

---

.github/workflows/deploy_dev.yml

Har ikke funnet en bedre måte å støtte input fra både `workflow_dispatch` og `repository_dispatch`.
Alternativt kan vi introdusere en til workflow som kun er for `repository_dispatch` / deploy-scriptet.

Støtter env variabler fra både worflow_dispatch og repository_dispatch

---

src/components/oppgaver/FilView.tsx
src/components/oppgaver/OppgaveView.tsx
src/components/oppgaver/oppgaver.less
src/components/vedlegg/EttersendelseView.tsx

Litt mer semantisk riktig å bruke knapper på elementer med `onClick` etc. Har også endret rekkefølgen på rendring av knapp og filer i `EttersendelseView` slik at tab-order blir riktig.

Bytter ut lenker for opplasting av filer med knapper

---

src/components/oppgaver/OppgaveView.tsx
src/components/vedlegg/EttersendelseView.tsx

Samme som for ettersendelse i søknaden. Legger på beforeunload handler slik at bruker kan få et varsel dersom de har valgt filer men ikke trykket på "Send" knapp.

Legger på beforeunload handler dersom vedlegg er valgt men ikke lastet opp

---

src/components/oppgaver/DokumentasjonEtterspurtView.tsx
src/components/oppgaver/onSendVedleggClicked.tsx
src/components/oppgaver/sendVedlegg.tsx
src/components/vedlegg/EttersendelseView.tsx
src/utils/vedleggUtils.test.ts
src/utils/vedleggUtils.ts

- SendVedlegg er tatt ut fra Ettersendelse og DokumentasjonEtterspurt
- SendVedlegg er gjort veldig enkelt i første omgang 
- Derfor tar den i mot 'undefined' i det parameter den ikke skal bruke
- Vi håndterer forskjellene mellom Ettersendelse og DokumentasjonEtterspurt med veldig enkle if statements
- Planen er i en senere pr å fortsette arbeidet med SendVedlegg
- Noen variabler har blitt renamed til engelsk.

Drar ut sendVedlegg til egen fil

---

server.js

for å kunne få noe oversikt over deploy på VM-ene.
I `sosialhjelp-innsyn.service` må `ExecStart` utvides med `-e IMAGE=${IMAGE}` også (gjort)

Logger image-tag ved oppstart

---

package-lock.json
package.json
src/axios-instance.ts
src/utils/vedleggUtils.ts

Det skjedde litt endringer i hvordan type `[brukes i 5.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-1.html#avoiding-unnecessary-type-instantiation)`, og derfor ble `(e instanceof AxiosError<T>)` endret til `e.isAxiosError`. Skal ha samme resultat.

Oppdaterer typescript fra 4.9.5 til 5.2.2

---

src/components/Infopanel/InfoPanel.tsx
src/components/Tilgangskontrollside/Tilgangskontrollside.tsx
src/components/arkfanePanel/ArkfanePanel.tsx
src/components/driftsmelding/Driftsmelding.tsx
src/components/eksternLenke/EksternLenke.tsx
src/components/ellaBlunk/index.tsx
src/components/filopplasting/AddFileButton.tsx
src/components/forelopigSvar/ForelopigSvar.tsx
src/components/historikk/Historikk.tsx
src/components/ikoner/AapnetBrev.tsx
src/components/ikoner/Dokument.tsx
src/components/ikoner/DokumentSendt.tsx
src/components/ikoner/GodkjentMerke.tsx
src/components/ikoner/InfoIkon.tsx
src/components/ikoner/LukketBrev.tsx
src/components/ikoner/Timeglass.tsx
src/components/lastestriper/Lasterstriper.tsx
src/components/oppgaver/IngenOppgaverPanel.tsx
src/components/oppgaver/vilkar/VilkarView.tsx
src/components/subheader/Subheader.tsx
src/components/vedlegg/VedleggModal.tsx
src/components/vedlegg/VedleggView.tsx
src/pages/404.tsx
src/saksoversikt/SaksoversiktDineSaker.tsx
src/saksoversikt/SaksoversiktIngenSoknader.tsx
src/saksoversikt/banner/UserIcon.tsx
src/saksoversikt/dineUtbetalinger/DineUtbetalingerPanel.tsx
src/saksoversikt/sakpanel/SakPanel.tsx
src/utbetalinger/UtbetalingsoversiktIngenInnsyn.tsx
src/utbetalinger/UtbetalingsoversiktIngenSoknader.tsx

React.FC considered deprecated, jamfør:
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/
Bruker derfor en codemod til å fjerne dem alle:
https://codemod.com/registry/react-replace-react-fc-typescript
Første commit var en best-guess på hvordan fikse en syntaksfeil

Fjerner foreldet "React.FC"-syntaks

---

next.config.js

vi tror og håper dette ikke er nødvendig nå som login-api er pensjonert
Testet i preprod, funker der

Fjerner trailingSlash i next config

---

src/middleware.ts

Dersom tilgang-kallet feiler, sendes brukeren til 500-siden, men den prøver jo også tilgangskallet.

bugfix: infinite redirect loop om tilgangskontroll feiler

---

next.config.js

Ville bare gjøre det litt mer leselig :)
Jeg sjekket [hvordan csp blir gjort i nav-dekoratoren](https://github.com/navikt/nav-dekoratoren/blob/main/packages/server/src/content-security-policy.ts), og fant ut at direktivene vi gir, flettes med direktivene dekoratoren gir, som inkluderer uxsignals og NAV CDN. Dermed var det en del som var dublert som vi kan fjerne fra vår side.
Jeg vet ingenting om `https://uxsignals-frontend.uxsignals.app.iterate.no`, men den var ikke i nav-dekoratorens liste så jeg beholder den.
Det er verdt å merke seg at én policy på connect-src blir innsnevret fra *.uxsignals.com til api.uxsignals.com fordi dette er nav-dekoratoren sin preset, siden det også er [verdien oppgitt i uxsignals' egen dok](https://app.uxsignals.com/docs#CSP), antar jeg connect-src bare var …

Refaktor av CSP directives
